# Menu config

[[main]]
identifier = "bodylanguage"
pre = ""
post = ""
name = "Body Language"
url = "/bodylanguage/"
title = ""
weight = 8

[[main]]
identifier = "contact"
pre = ""
post = ""
name = "Contact"
url = "/contact/"
title = ""
weight = 8